Scalar.UnitTests/Common/Git/GitSslTests.cs
During the port to .NET Core 3, we missed the fact that the `GitSslTests` test fixture was being conditionally compiled only when `NETCOREAPP_21` was defined.
Removing the `#if` directive and always including those tests.
=> Add missing Git SSL/TLS unit tests

Dependencies.props, Directory.Build.props, Scalar.Common/NuGetUpgrade/NuGetFeed.cs, Scalar.Common/NuGetUpgrade/NuGetUpgrader.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Common/Platforms/POSIX/POSIXPlatform.cs, Scalar.Common/ProcessHelper.cs, Scalar.Common/Scalar.Common.csproj, Scalar.Common/ScalarPlatform.cs, Scalar.Installer.Windows/Scalar.Installer.Windows.csproj, Scalar.MSBuild/GenerateScalarConstants.cs, Scalar.Service.UI/Scalar.Service.UI.csproj, Scalar.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs, Scalar.UnitTests/Common/NuGetUpgrade/OrgNuGetUpgraderTests.cs, Scripts/BuildScalarForWindows.bat, Scripts/CI/CreateFTDrop.bat, Scripts/RunFunctionalTests.bat
The NuGet SDK for .NET Core does not support verification of NuGet packages, even on Windows. We instead bundle a copy of nuget.exe on Windows installs of Scalar and shell out to the CLI tool to perform validation. The tool must be Authenticode signed before we delegate package verification to it.
This change also makes us target builds to Windows 10 64-bit specifically.
Because we have a dependency on PowerShell, which itself has native dependencies that are tied to specific Windows versions, we must pick a (minimum) Windows version for Scalar to support. We select Windows 10, mainly because Windows 7 is now out of support, and we only test for Windows 10.
=> Fix verification of upgrade packages

Dependencies.props, Directory.Build.props, Scalar.Common/NuGetUpgrade/NuGetFeed.cs, Scalar.Common/NuGetUpgrade/NuGetUpgrader.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Common/Platforms/POSIX/POSIXPlatform.cs, Scalar.Common/ProcessHelper.cs, Scalar.Common/Scalar.Common.csproj, Scalar.Common/ScalarPlatform.cs, Scalar.Installer.Windows/Scalar.Installer.Windows.csproj, Scalar.MSBuild/GenerateScalarConstants.cs, Scalar.Service.UI/Scalar.Service.UI.csproj, Scalar.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs, Scalar.UnitTests/Common/NuGetUpgrade/OrgNuGetUpgraderTests.cs, Scripts/BuildScalarForWindows.bat, Scripts/CI/CreateFTDrop.bat, Scripts/RunFunctionalTests.bat
The NuGet SDK for .NET Core does not support verification of NuGet packages, even on Windows. We instead bundle a copy of nuget.exe on Windows installs of Scalar and shell out to the CLI tool to perform validation. The tool must be Authenticode signed before we delegate package verification to it.
This change also makes us target builds to Windows 10 64-bit specifically.
Because we have a dependency on PowerShell, which itself has native dependencies that are tied to specific Windows versions, we must pick a (minimum) Windows version for Scalar to support. We select Windows 10, mainly because Windows 7 is now out of support, and we only test for Windows 10.
This is a port of #317 to the 20.01.165 release branch.
=> [port rel165] Fix verification of upgrade packages

Scalar.FunctionalTests/Tests/EnlistmentPerFixture/DiagnoseTests.cs, Scalar/CommandLine/DiagnoseVerb.cs
The SecureDataRoot and CommonAppDataRoot are the same on Mac, so we were
double-copying files from the same place when running 'scalar diagnose'.
We also never ran the diagnose verb in the functional tests, so fix
that.
=> DiagnoseVerb: fix colliding files on Mac

Directory.Build.props
See microsoft/git#240 and microsoft/git#243.
Because of #320, we do not need to update the minimum Git version from `v2.25.0.vfs.1.1` even though we are packaging with `v2.25.0.vfs.1.3` now.
=> Update Git to v2.25.0.vfs.1.3 to include disabled fetch-pack and block 'git update'

Scalar.Common/Maintenance/ConfigStep.cs
I was perusing my logs when I found the following error:
```
System.IO.IOException: The file 'C:\\_git\\scalar\\src\\.git\\hooks\\query-watchman' already exists.
at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
at Scalar.Common.FileSystem.PhysicalFileSystem.CopyFile(String sourcePath, String destinationPath, Boolean overwrite) in E:\\A\\_work\\23\\s\\Scalar.Common\\FileSystem\\PhysicalFileSystem.cs:line 75
at Scalar.Common.Maintenance.ConfigStep.ConfigureWatchmanIntegration() in E:\\A\\_work\\23\\s\\Scalar.Common\\Maintenance\\ConfigStep.cs:line 250
"ErrorMessage":"Failed to configure Watchman integration: The file …
```
=> ConfigStep: don't fail copying over existing hook

Scalar.FunctionalTests/Tests/GitRepoPerFixture/RunVerbTests.cs, Scalar.FunctionalTests/Tools/ScalarFunctionalTestEnlistment.cs, Scalar.FunctionalTests/Tools/ScalarProcess.cs, Scalar/CommandLine/RunVerb.cs
Resolves #328.
If another process holds a write lock on the `.git/logs/scalar_maintenance_service.log` file, then the process exits with an `IOException` stack trace.
Instead of failing, first try creating a log file using a timestamp and logging the first exception. If that fails, then write an error to output and continue with the command.
=> RunVerb: fall back to timestamp log if service log is busy

Scalar.Common/FileBasedDictionary.cs, Scalar.Common/Git/GitCredentialManagerProcess.cs, Scalar.Common/NuGetUpgrade/NuGetFeed.cs, Scalar.Common/ProcessHelper.cs, Scalar.Common/ScalarConstants.cs, Scalar.Common/ScalarPlatform.cs, Scalar.MSBuild/GenerateScalarConstants.cs, Scalar.UnitTests/Git/GitCredentialManagerProcessTests.cs, Scalar.Upgrader/UpgradeOrchestrator.cs, Scalar/CommandLine/UpgradeVerb.cs
If Git is not installed, try to use a bundled GCM binary drop for getting credentials for use in Upgrade. This can help in bootstrapping scenarios where the user does not have an installed copy of Git/GCM.
=> Use a bundled GCM Core if Git is not installed

Scalar.Common/Enlistment.cs, Scalar.Common/Git/GitAuthentication.cs, Scalar.Common/Git/GitSsl.cs, Scalar.Common/Http/CacheServerResolver.cs, Scalar.Common/InvalidRepoException.cs, Scalar.Common/ScalarEnlistment.cs, Scalar.UnitTests/Common/Git/GitSslTests.cs, Scalar.UnitTests/Git/GitAuthenticationTests.cs, Scalar/CommandLine/ScalarVerb.cs
This should make errors like those in #332 a bit cleaner. With this change, those failures will no longer exit with a stack trace and crash, but instead exit with an error code. The error message will include which path we are trying to use for the Git repository path.
Resolves #333.
=> Make InvalidRepoException exit normally

Scalar.Common/Maintenance/ConfigStep.cs
Watchman wasn't getting configured during clone but was once the maintenance step ran.  It should really be configured in both place.  At clone time and when maintenance runs.
=> Configure watchman when setting config so it will happen at clone time

Scalar.Common/Maintenance/ConfigStep.cs
Resolves #338.
This appears to be the issue:
1. Someone runs `scalar register` in a repository that has worktrees.
2. The worktrees start to use the `core.fsmonitor` config setting.
3. The worktree tries to execute from `.git/hooks/query-watchman`, but that is not a path relative to the worktree.
This fixes the configs setting.
I've tested this on my Windows machine with a worktree of git/git.
Cc: @kewillford the expert on fsmonitor. As a longer plan, we should consider adding tests that cover the case for worktrees.
=> ConfigStep: use full hook path for fsmonitor

Directory.Build.props, Scalar.Common/Git/GitAuthentication.cs, Scalar.Common/Git/GitProcess.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ScalarCloneFromGithub.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/TestsWithMultiEnlistment.cs, Scalar.FunctionalTests/Tools/ScalarFunctionalTestEnlistment.cs, Scalar/CommandLine/CacheServerVerb.cs, Scalar/CommandLine/CloneVerb.cs, Scalar/CommandLine/RunVerb.cs, Scalar/CommandLine/ScalarVerb.cs
This requires microsoft/git#249 in order to avoid a bad partial clone bug.
You can now try this:
```
$ scalar clone https://github.com/microsoft/scalar
Clone parameters:
Repo URL:     https://github.com/microsoft/scalar
Branch:       Default
Cache Server: Default
Local Cache:  C:\.scalarCache
Destination:  C:\_git\t\scalar
FullClone:     False
Authenticating...Succeeded
Fetching objects from remote...Succeeded
Checking out 'master'...Succeeded
$ ls scalar/src/
AuthoringTests.md  Dependencies.props     Directory.Build.targets  License.md    Protocol.md  Scalar.ruleset  SECURITY.md
CONTRIBUTING.md    Directory.Build.props  global.json              nuget.config  Readme.md    Scalar.sln      Signing.targets
$ cd scalar/src/
$ git sparse-checkout disable
remote: Enumerating objects: 418, done. …
```
=> CloneVerb: Fall back to partial clone

Scalar.Common/Enlistment.cs, Scalar.Common/InvalidRepoException.cs, Scalar.Common/ScalarEnlistment.cs, Scalar.UnitTests/Common/ScalarEnlistmentTests.cs, Scalar.UnitTests/Mock/Common/MockScalarEnlistment.cs, Scalar/CommandLine/CloneVerb.cs, docs/advanced.md
Resolves #350 
While playing around with an empty repository, I found that `scalar diagnose` was failing because it was adding `src` to the working directory. Turns out there is a missed path that happens depending on the verb options, and now it is fixed.
While doing that, improve the message for `InvalidRepoException`.
=> Allow repositories without an 'origin' remote

Directory.Build.props, Scalar.Common/Maintenance/ConfigStep.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Common/Platforms/Windows/WindowsPlatform.cs, Scalar.Common/ScalarConstants.cs, Scalar.Common/ScalarPlatform.cs, Scalar.FunctionalTests/Tests/GitCommands/GitCommandsTests.cs, Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs, Scalar.FunctionalTests/Tools/ControlGitRepo.cs, Scalar.FunctionalTests/Tools/GitHelpers.cs, Scalar.TestInfrastructure/Should/EnumerableShouldExtensions.cs, Scalar.UnitTests/Mock/Common/MockPlatform.cs
See microsoft/git#251 for details.
A few reaction items needed to happen:
1. We need to ignore whitespace lines when verifying Git commands. Some added an extra whitespace line.
2. The rebase backend changed, and it causes `git rebase --continue` to open an editor if the commit had conflicts. By changing `core.editor=true`, we can no-op the editor portion instead of running forever with an open `vi` editor.
3. With the updated rebase backend, the commit OID is written to output. This causes our output between the control repo and the Scalar repo to be different. Set `GIT_COMMITTER_DATE` to be constant to avoid this problem.
4. The `fsmonitor` hook version was updated, so we need to update our hook along with Git. By copying from the templates directory instead of the samples initialized …
=> Update Git to v2.26.0

Scalar.Installer.Mac/InstallScalar.template.sh
Resolves #336.
Since `sudo whoami` always returns "root", we should not just replace our use of `logname` with `whoami`. Instead, fall back to `whoami` only if `logname` returns "root".
=> Mac install: use 'whoami' for user name

Scalar.Common/Maintenance/ConfigStep.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Installer.Mac/InstallScalar.template.sh
In #349, we updated where the hooks were being copied from. Instead of
the local .git/hooks directory, we copy from the installed templates
directory. This allowws us to grab the latest hook associated with our
Git version.
However, I neglected testing thoroughly on Mac, and the path was not
rooted. This causes the config step to log an error because the path
starts at the current working directory, not from root.
Adjust the ConfigStep to return a 'false' result when this step fails,
which will cause the RunVerbTests to fail if we cannot set the hook as
expected.
The test does not verify the hook is placed because we only place it if
Watchman is installed.
Also, I noticed that the templates directory was wrong! Our installer
puts the templates in a different place than another version of …
=> Mac: fully root path to '/usr/local' for hook location

Directory.Build.props, Scalar.Common/Git/GitProcess.cs, Scalar.UnitTests/Maintenance/CommitGraphStepTests.cs
Wow, this was really not working as expected.
See microsoft/git#255 for how broken the `--expire-time` argument was.
Fix this by using the fixed argument and passing a datetime instead of an offset by seconds. This will provide a longer window for old commit-graph files, but apparently we've been leaving turd files around for a long time without anyone noticing.
=> Fix commit-graph expiration

Directory.Build.props
Re-pushed to include the correct version number after pushing the `v2.26.1.vfs.1.1` tag.
=> Update Git to include v2.26.1

Directory.Build.props
This time with the correct version number.
See #366 for the PR into master.
=> [M168] Update Git to include v2.26.1

Scalar.Common/Maintenance/ConfigStep.cs
Scalar has already been managing multiple pack files situation with
multi-pack-index. This means that adding packs to the git repo is
relatively low cost.
Reducing `fetch.unpackLimit` to 1 (from default value of 100) assures
that all the fetch will store transferred pack as-is on disk, instead
of spending computation to unpack data into loose objects. This
should make fetching a little bit faster for large fetch that could
be unpacked into many objects (i.e. 99 objects since the default ).
These objects, instead of being unpacked and written onto disk, is then
kept as packfile and get consolidated with incremental repack step using
multi-index-pack.
On a busy repo, this potentially might make incremental repack with
multi-pack-index works a bit harder. But I think this worth the …
=> Reduced fetch.unpackLimit to minimum

Directory.Build.props, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/SparseSetTests.cs, Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs, Scalar/CommandLine/CloneVerb.cs
Also fixes a bug when running `scalar clone` followed by `git sparse-checkout disable`.
See microsoft/git#267.
=> Update Git to include en/sparse-checkout

Directory.Build.props, Scalar.Common/Git/GitProcess.cs, Scalar.Common/Maintenance/ConfigStep.cs, Scalar.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
See microsoft/git#271.
Updates necessary here:
* The `multi-pack-index` builtin started honoring `repack.packKeptObjects`, which is `false` by default. We want to repack the `.keep` pack because that is just the most-recent prefetch pack-file. We don't expire it, but we want to repack it.
* Upstream now has the `log.excludeDecoration` config option. This allows us to hide the `refs/scalar/hidden/*` refs from the history views, de-cluttering the history for our Scalar enlistments.
=> Update Git to v2.27.0

Scalar.Common/Maintenance/GitMaintenanceStep.cs, Scalar.Common/Maintenance/LooseObjectsStep.cs, Scalar.Common/Maintenance/PackfileMaintenanceStep.cs, Scalar.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
When the total size of all pack-files is larger than 2 gigabytes, then
we currently use a strange mechanism for trying to repack everything
else into a single pack.
The "estimated output size" that we use for predicting the batch size
will under-count pack sizes when there are duplicates. This means that
the current model will actually no-op most of the time! By picking the
second-largest file size, the `repack` command will have a high
likelihood of doing _something_, and that size will grow geometrically
as we go. This strategy was recommended by @sluongng and it seems
to work better.
This only affects "small" repos. We will use 2 gigabytes as the
default batch-size for large repos.
=> PackfileMaintenanceStep: Use second-largest pack-size for batch size

Scalar.Common/Maintenance/ConfigStep.cs
A VFS for Git user noticed extremely slow "git status" times, and the
root cause was that they had set status.submoduleSummary=true in their
global config. This causes two "git submodule" subprocesses, which are
very slow. The GVFS protocol does not allow submodules, so disable the
setting when using that protocol.
I investigating fixing this in Git proper, but there is no efficient
way to detect that we can ignore this setting since there could be
an untracked submodule.
=> ConfigStep: disable status.submoduleSummary when using GVFS protocol

.azure-pipelines/pull-request.yml, AuthoringTests.md, CONTRIBUTING.md, Readme.md, Scalar.Common/Git/GitRefs.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/SparseSetTests.cs, Scalar.FunctionalTests/Tests/GitRepoPerFixture/RunVerbTests.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ScalarCloneFromGithub.cs, docs/getting-started.md, docs/index.md
I updated the default branch to `main`, so this is the work required to get builds and things going against that branch.
There is more work to be done to update the default branch for repos _cloned_ by Scalar, but that will be a behavior change that we should handle after Git has a clear way forward.
=> Change default branch to `main`

Readme.md, Scalar.Common/Maintenance/ConfigStep.cs, docs/getting-started.md, docs/index.md
1. @fornever [reported a doc bug](https://github.com/microsoft/scalar/commit/da87cb27c22c6a1b4c470c03738ade1450c1210a#r40061740) with the `main` branch which doesn't exist in microsoft/vfsforgit.
2. @sluongng pointed out that `checkout.optimizeNewBranch` doesn't exist anymore. Resolves #388.
3. @nikola-sh requested that `core.autocrlf` and `core.safecrlf` be optional. Resolves #391.
=> Small cleanups

Scalar/CommandLine/ScalarVerb.cs
A user reported issues with parsing our Git version when cloning. Our
best guess of what happened is that the build machine already had a
version of Git, but it was in a different location whan where our `brew`
formula placed our version of Git. This led the parser to not see a
`.vfs.` in the version string and fail.
Let's make this error more informative. While we are here, split the
failure condition into two distinct cases:
1. We can't find Git anywhere.
2. We can't parse the Git version.
Signed-off-by: Derrick Stolee <dstolee@microsoft.com>
=> CheckGitVersion: improve error messages

Scalar.FunctionalTests/Tools/ControlGitRepo.cs
Support for 'git branch --set-upstream' was finally dropped in v2.15 and
now causes Git to call die().  See 52668846ea2d41ffbd87cda7cb8e492dea9f2c4d.
Update our usage in the functional test suite to use the new form:
'git branch --set-upstream-to'.
This was causing 70+ Git commands to fail in the functional test suite
(from the error alone and an unknown number of tests to fail because
the worktree was not updated as expected).
Signed-off-by: Jeff Hostetler <jeffhost@microsoft.com>
=> ControlGitRepo.cs: switch to 'git branch --set-upstream-to'

Scalar.FunctionalTests/Tools/GitHelpers.cs, Scalar.FunctionalTests/Tools/GitProcess.cs
Use the GIT_TRACE2_ENV_VAR feature to insert the full name of the
NUnit TestCase into the Trace2 output stream.
This only covers Git invocations that use the Functional Test
harness (and not the ones using the Common/GitAPI mechanism).
This now also includes a sequence number to match up control and enlistment command pairs.
=> GitProcess: add NUnit TestCase FullName to trace2 output

Scalar.Common/Git/GitFeatureFlags.cs, Scalar.Common/Git/GitVersion.cs, Scalar.UnitTests/Common/GitVersionTests.cs, Scalar/CommandLine/CloneVerb.cs
Add a way to get a list of features that a version of Git supports, such as support for the GVFS protocol.
With this we can better handle and support users of Scalar that are not using Azure DevOps or the Microsoft fork of Git.
In the future we can also gate behaviour on other features such as `--changed-paths`.
Implements #380
**TODO:**
=> Detect Git features (the GVFS Protocol) based on the version

.github/workflows/homebrew-release.yml
Add a GitHub workflow that is triggered on creation and publish of a release on GitHub, to update the `scalar` and `scalar-azrepos` Casks on the microsoft/git Homebrew Tap.
=> Add workflow to auto update Homebrew Casks

Directory.Build.props, Scalar.Common/Maintenance/ConfigStep.cs, Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs
See microsoft/git#283.
The new logic around `core.repositoryFormatVersion` and `extensions.*` config options causes problems in Scalar due to our use of sparse-checkout. This is resolved by some upstream fixes and some more careful config here.
=> Update Git to v2.28.0

Directory.Build.props, Scalar.Common/Git/GitProcess.cs, Scalar.Common/Maintenance/ConfigStep.cs, Scalar.Common/Maintenance/GitMaintenanceStep.cs, Scalar.Installer.Windows/InstallScalar.template.bat, Scalar/CommandLine/ScalarVerb.cs
These cleanups were discovered while working on #398:
1. Update Watchman download to get newer version. (Link was broken by recent change in release process.)
2. Use a better error when downloading the tip commit fails.
3. Use multi-valued config for `log.excludeDecoration` since it will need multiple values.
4. Do a better job interacting with `GIT_OBJECT_DIRECTORY` in `GitProcess`.
5. Stop exiting on an unknown exception during `GitMaintenanceStep`.
=> Minor cleanups

Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ScalarCloneFromGithub.cs
This string was added when toying with testing SSH URLs in the
functional tests. However, there was an issue with using SSH inside the
build machines, so it was never used. It's now creating pain for the
GitHub Actions workflows that will build Scalar. Drop it.
(This was noticed by the warnings in #413.)
=> ScalarCloneFromGitHub: drop SSH string

Scalar.FunctionalTests/Categories.cs, Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ConfigVerbTests.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/SharedCacheTests.cs
Prior to starting work to support runs of the functional test suite on Linux, we can simplify some of the tests marked `MacTODO` as no longer needing that designation and also simplify some of the Windows-related configuration and options.
On the Windows side of thing, we can remove the second invocation of `excludeCategories.Add(Categories.MacOnly)` because it is always performed on Windows in the `if/else` block just above it.
We also only parse the `--windows-only` functional test command-line option when running on Windows, as it has no effect on macOS since the `WindowsOnly` tests are always excluded there.
On the macOS side of things, there is one test still marked `MacTODO.NeedsServiceVerb` which appears to have been missed in PR #216, where that category was removed from many …
=> Clean up functional test MacTODO categories and Windows-only option

.github/workflows/continuous-integration.yml
We define GitHub Actions YAML which runs a simplified version of the `BuildScalarFor*.{bat,sh}` and `RunUnitTests.{bat,sh}` scripts under `Scripts/`.  We run these jobs on all PRs to the `main` branch.
One difference is that we use a `Release` build configuration instead of using a `Build` configuration as our default.
We also do not define the `ScalarVersion` MSBuild property and instead rely on what is [set](https://github.com/microsoft/scalar/blob/ef5c1bc753d0e129a2ca27c0e4daee78a27d1d30/Directory.Build.props#L38) in `Directory.Build.props`.
We include builds on three Ubuntu versions to align with what [runs](https://github.com/microsoft/Git-Credential-Manager-Core/blob/2e9919d0b8017dcbde244d129d3b321effe1ab59/.github/workflows/continuous-integration.yml#L16) for GCM Core, and to …
=> Setup GitHub Actions build and unit test CI jobs

Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/ScalarTestConfig.cs, Scalar.FunctionalTests/Settings.cs, Scalar.FunctionalTests/Tools/GitProcess.cs
We implement the equivalent of the existing `--test-scalar-on-path` functional test command-line option for Git also, namely by adding a new `--test-git-on-path` option.
This permits the manual execution of the functional test suite on systems where the default installation of Git may not be sufficient to support Scalar; i.e., it may be an older version or not the Microsoft Git [custom package](https://github.com/microsoft/git).
The existing CI jobs are not affected by this change as the default when the new command-line option is not provided is to continue to look for Git as `C:\Program Files\Git\cmd\git.exe` on Windows and `/usr/local/bin/git` on macOS, as the functional test program did before.
=> Allow functional tests to use Git from $PATH

Directory.Build.props, Scalar.Common/Platforms/Linux/LinuxFileBasedLock.cs, Scalar.Common/Platforms/Linux/LinuxFileSystem.cs, Scalar.Common/Platforms/Linux/LinuxPlatform.Shared.cs, Scalar.Common/Platforms/Linux/LinuxPlatform.cs, Scalar.Common/Platforms/Linux/LinuxProductUpgraderPlatformStrategy.cs, Scalar.Common/Platforms/PlatformLoader.cs, Scripts/Linux/BuildScalarForLinux.sh, Scripts/Linux/InitializeEnvironment.sh, Scripts/Linux/NukeBuildOutputs.sh, Scripts/Linux/RunUnitTests.sh
This is an initial port of the `GVFS.Platform.Linux` classes and the `Scripts/Linux` scripts from both the Mac equivalents in this repository as well as the corresponding classes in the VFSForGit repository.
Note that some useful refactoring which exists in the VFSForGit `features/linuxprototype` [branch](https://github.com/microsoft/VFSForGit/tree/features/linuxprototype), such as microsoft/VFSForGit@7b708506165aaa39783f9bc4d193e9cf39ebc85f, has not yet been ported; this would (re-)eliminate some of the duplication between the Mac and Linux platforms and move common code into the POSIX one.
This PR also does not include the case-sensitive filename support in VFSForGit's `master` branch from microsoft/VFSForGit#1412.
Quoting from the primary VFSForGit commit microsoft/VFSForGit@b304cf7 …
=> Add initial Linux platform and scripts

.azure-pipelines/templates/osx/functional-test.yml, .azure-pipelines/templates/win/functional-test.yml, AuthoringTests.md, Scalar.FunctionalTests/Categories.cs, Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/CacheServerTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/FetchStepWithoutSharedCacheTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/ScalarUpgradeReminderTests.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ConfigVerbTests.cs, Scripts/Mac/RunFunctionalTests.sh
This PR aims to simplify the options for the functional test program, align them between macOS and Windows (including in CI), update the relevant documentation, and fix a failing test so it runs and passes on all platforms.
It may be easiest to review commit-by-commit, but I've also tried to put all of the relevant background into this description as well.
----
The CI jobs run `Scripts\RunFunctionalTests.bat --test-scalar-on-path` on [Windows](https://github.com/microsoft/scalar/blob/562f127885580baee20769b981da0601787481d8/.azure-pipelines/templates/win/functional-test.yml#L35) and `Scripts/Mac/RunFunctionalTests.sh --test-scalar-on-path` on [macOS](https://github.com/microsoft/scalar/blob/562f127885580baee20769b981da0601787481d8/.azure-pipelines/templates/osx/functional-test.yml#L43). …
=> simplify and align functional test CI and docs, and fix failing skipped test

Scalar.FunctionalTests/Categories.cs, Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/FetchStepTests.cs
The `FetchStepCleansUpStaleFetchLock()` functional test currently only succeeds on Windows (and is therefore marked with the `MacTODO.TestNeedsToLockFile` category) because it checks whether the `FetchStep` command has released its lock file by testing if the lock file has been deleted.
This works with our `WindowsFileBasedLock` implementation, which opens the lock file with `FileOptions.DeleteOnClose`, so the file is removed when the lock is released.  However, the `MacFileBasedLock` version leaves the file in place and uses [`flock(2)`](https://man7.org/linux/man-pages/man2/flock.2.html) and `LOCK_EX` to acquire and release the lock atomically; there is no simple way to delete the file while still holding the open file descriptor needed for `flock()`.
To make this test succeed on …
=> enable FetchStepTests on Mac/Linux and remove MacTODO test categories

Dependencies.props, Scalar.Common/Platforms/Linux/LinuxPlatform.Shared.cs, Scalar.Common/Platforms/Linux/LinuxPlatform.cs, Scalar.Common/Platforms/Mac/MacPlatform.Shared.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Common/Platforms/POSIX/POSIXPlatform.cs, Scalar.Common/Scalar.Common.csproj, Scalar.Common/ScalarConstants.cs, Scalar.FunctionalTests/Categories.cs, Scalar.FunctionalTests/FileSystemRunners/FileSystemRunner.cs, Scalar.FunctionalTests/FileSystemRunners/SystemIORunner.cs, Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/ScalarTestConfig.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/CloneTests.cs, Scalar.FunctionalTests/Tests/GitCommands/GitCommandsTests.cs, Scalar.FunctionalTests/Tools/TestConstants.cs, Scripts/Linux/CleanupFunctionalTests.sh, Scripts/Linux/RunFunctionalTests.sh
This PR adds functional test scripts for Linux, adjusts a number of Mac-specific syscall wrappers and `FileSystemRunners` to be either POSIX-generic or have Linux-specific equivalents, makes some minor updates to align Linux packaging details with other platforms, and refactors the setup of the cache, config, and data directories on POSIX platforms to support (in the Linux case only) the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
It should be possible to review either commit-by-commit or as a single set of changes; the former might be slightly easier, though.
---
The (partial) support for the XDG specification comprises the majority of the changes in this PR, and is motivated by the fact that the functional tests …
=> Linux: functional test and XDG configuration support

.github/workflows/continuous-integration.yml
To run the functional test suite in GitHub Actions, we write platform-specific steps to install the GVFS Git package, but then use a single common step to run the functional tests themselves.
The Actions YAML steps added in this PR resulted in a recent [successful run](https://github.com/chrisd8088/scalar/runs/1103660793) on all platforms.
This PR builds on #422, which adds functional test support on Linux, and can be rebased once that PR is accepted and merged into `main`.
---
The commands in the Git installer steps are drawn in part from those found in the existing `Scalar.Installer.{Mac,Windows}/InstallScalar.template.{sh,bat}` scripts.
On Windows, we specifically need to ensure that our version of Git is the one in `C:\Program Files\Git\cmd\git.exe`, so we start install process by …
=> Actions: run functional tests on all platforms (without Watchman)

Readme.md, docs/index.md, docs/philosophy.md
Our Readme.md file is not incredibly helpful. We have changed a lot about our install/upgrade strategy, particularly for macOS. I have fielded several questions about this over email or in issues (e.g. #399).
This PR is a start to revamping our documentation a bit. The Readme now points to the more involved `docs/index.md`. That directory also gets a "Philosophy of Scalar" document, which I will point to people who are wondering if Scalar is right for them.
You can see how this Readme looks at the front page of a repo [by looking at my fork](https://github.com/derrickstolee/scalar/tree/readme).
Resolves #384.
=> Update Readme.md and documentation with helpful info

Readme.md, Scalar.Common/ConsoleHelper.cs, Scalar.Common/Git/GitProcess.cs, Scalar.Upgrader/UpgradeOrchestrator.cs, Scalar/CommandLine/CloneVerb.cs, Scalar/CommandLine/ScalarVerb.cs
Ensure authentication prompts shown by Git and any configured credential
helpers can write to the terminal/TTY and capture information.
We don't _really_ need the fancy spinner to show "Authenticating...";
this is only cosmetic.
Also explicitly pass-down the userInteractive=true argument down the
call stack to the construction of the Git process, and move the setting
of GIT_TERMINAL_PROMPT=0 into the if-not-user-interactive block.
=> Remove spinner from all progress (allow auth prompts to use the terminal)

Scalar.Common/GitHubUpgrader.cs, Scalar.Common/Maintenance/FetchStep.cs, Scalar.Common/Maintenance/GitMaintenanceStep.cs, Scalar.Common/Maintenance/GitProcessChecker.cs, Scalar.Common/Maintenance/PackfileMaintenanceStep.cs, Scalar.Common/Platforms/Linux/LinuxFileSystem.cs, Scalar.Common/Platforms/Linux/LinuxPlatform.cs, Scalar.Common/Platforms/Mac/MacFileSystem.cs, Scalar.Common/Platforms/Mac/MacPlatform.cs, Scalar.Common/Platforms/POSIX/POSIXFileSystem.cs, Scalar.Common/Platforms/POSIX/POSIXPlatform.cs, Scalar.Common/Platforms/Windows/WindowsFileSystem.cs, Scalar.Common/Platforms/Windows/WindowsPlatform.cs, Scalar.Common/ScalarPlatform.cs, Scalar.FunctionalTests/FileSystemRunners/CmdRunner.cs, Scalar.FunctionalTests/Should/FileSystemShouldExtensions.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/CloneTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/FetchStepTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/FetchStepWithoutSharedCacheTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/GitCorruptObjectTests.cs, Scalar.FunctionalTests/Tests/GitCommands/UpdateRefTests.cs, Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ScalarCloneFromGithub.cs, Scalar.FunctionalTests/Tools/FileSystemHelpers.cs, Scalar.UnitTests/Common/FileBasedDictionaryTests.cs, Scalar.UnitTests/Common/PhysicalFileSystemDeleteTests.cs, Scalar.UnitTests/Mock/Common/MockPlatform.cs, Scalar.UnitTests/Mock/FileSystem/MockFileSystem.cs, Scalar/CommandLine/CloneVerb.cs, Scalar/CommandLine/DiagnoseVerb.cs, docs/faq.md
Use filesystem-specific case matching when comparing file paths throughout Scalar and the functional test suite.
The primary change in this PR is to introduce a pair of wrappers which we use in place of `StringComparison.OrdinalIgnoreCase` and `StringComparer.OrdinalIgnoreCase` throughout the codebase whenever we need to compare or match file names or paths.
These new comparison utilities are named `ScalarPlatform.Instance.Constants.Path{Comparison,Comparer}` in the main Scalar project, and have equivalents named `FileSystemHelpers.Path{Comparison,Comparer}` in the functional test program's project.
From microsoft/VFSForGit#1232, microsoft/VFSForGit#1412, and microsoft/VFSForGit#1503, with additional new work and tests.
Given its scope this PR is probably best reviewed commit-by-commit; …
=> use platform-specific filepath matching and add or revise relevant tests

.github/workflows/continuous-integration.yml, Scalar.FunctionalTests/FileSystemRunners/SystemIORunner.cs, Scalar.FunctionalTests/Tools/GitHelpers.cs, Scalar/CommandLine/CloneVerb.cs, Scripts/Mac/RunFunctionalTests.sh
We add Watchman-enabled runs of the functional test suite on all GitHub Actions runners for all three platforms.
The code changes in this PR are primarily the result of needing to work around some inconsistent behaviour from Watchman when running on macOS Catalina, which is used by the Actions macOS runners.  As described in facebook/watchman#858, creating a hard link to an existing inode from inside the watched Git working tree may not be reported to Git as a new file if the inode's other, existing "source" path (as passed to `link(2)`) resides outside the watched directory.
This problem is tickled by our functional test suite because the [`MoveFileFromOutsideRepoToInsideRepoAndAdd()`](https://github.com/microsoft/scalar/blob/7a86016e9bb7a6c7560a87aba2c7c0739f896571/Scalar.FunctionalTests …
=> add Watchman-enabled functional tests to GitHub Actions CI

Scalar.FunctionalTests/FileSystemRunners/BashRunner.cs, Scalar.FunctionalTests/FileSystemRunners/CmdRunner.cs, Scalar.FunctionalTests/FileSystemRunners/FileSystemRunner.cs, Scalar.FunctionalTests/FileSystemRunners/PowerShellRunner.cs, Scalar.FunctionalTests/FileSystemRunners/SystemIORunner.cs
We can prune the various negative "should fail" and "should not" methods from the `FileSystemRunner` classes as these are no longer utilized by any tests.
These methods were previously used by the `BasicFileSystemTests` and `MoveRenameFolderTests`, which were removed in commit d748084d852759e3e6c7c1e657452e2e75adf666.
Three additional methods could also be removed from these runner classes, namely `FileSize()`, `ReplaceFile()`, and `RenameDirectory()`.  I left them in because it seemed like they might be more obviously useful in the future than the "negative" methods.
OTOH these three additional unused methods could also be pruned now and then resurrected from Git history if they are ever needed again.  If the latter is preferred, I can add commit d32582c17c85a130293c3b394cddd3fddbb59cc0 …
=> FunctionalTests: drop unused negative runner methods

Scalar.Common/Git/GitProcess.cs, Scalar/CommandLine/CloneVerb.cs
Attempt to determine the remote's default branch name when performing a `scalar clone` using the vanilla Git protocols (not using the GVFS helper).
Use `ls-remote` to lookup the `HEAD` ref on the remote, and parse the results. If the remote's `HEAD` is not a branch, or we fail to parse the output for any reason, consult Git itself for the default branch name as a fallback.
Scalar clones using the GVFS protocol & helper work differently, and already take the default remote branch name from the manual call to `/info/refs?service=git-upload-pack`.
Fixes #438
=> Respect remote default branch name on vanilla Git clone

Scalar/CommandLine/RunVerb.cs
The ConfigStep makes a decision about calling 'git maintenance start'
depending on the platform (Linux only for now) and the Git version.
However, the code for computing the feature flags is in ScalarVerb and
needs to be injected by passing it through the ConfigStep constructor.
This was missed in the earlier work that inserted this into other
maintenance steps.
This fixes a feature that should have been introduced in #398.
=> RunVerb: pass git features to ConfigStep

Directory.Build.props
=> Update Git to v2.29.0

.github/workflows/build-installers.yml, Scalar.Packaging.Linux/Scalar.Packaging.Linux.csproj, Scalar.Packaging.Linux/build.sh, Scalar.sln
Build Debian packages for the Linux build of Scalar, as well as a tarball and symbol tarball. Upload these as artefacts as part of a GitHub workflow.
When building locally via `dotnet` CLI or `Scripts/Linux/BuildScalarForLinux.sh`, the Debian packages and tarballs can be found in `../out/Scalar.Packaging.Linux/(deb|tar)`.
=> Build Debian packages and tarball for Linux builds

Scalar.Signing/PostSignFiles.Mac.cmd, Scalar.Signing/PreSignFiles.Mac.cmd, Scalar.Signing/Scalar.SignFiles.Mac.csproj
This is a cherry-pick of a commit I pushed to `releases/20.10.178` to fix macOS signing problems in the `microsoft.scalar-release` build.
The `scalar.upgrader` project was removed from macOS in #412, but we didn't run the signing until release time.
=> SignFiles: drop upgrader on macOS

Readme.md, docs/index.md
Our [latest release](https://github.com/microsoft/scalar/releases) includes our very first version available for Linux!
This PR adds documentation to the `Readme.md` at the repo root and the `docs/index.md` file for assistance downloading and installing Git and Scalar from the `.deb` packages. These documents will expand as we expand the installation options, including `apt-get` packaging.
=> Docs: include Linux install instructions

.github/run_esrp_signing.py, .github/workflows/build-signed-deb.yml
Port Debian package signing workflow and scripts from GCM Core.
This is a "good enough for now" state; we should revisit these scripts and clean them up, when we look to port Windows and macOS signing to this model.
=> Port Debian package signing

Directory.Build.props
Thanks to @kyle-rader and @mjcheetham, we have signed Linux builds for `microsoft/git`. This updates the package to [the signed version of the same Git code](https://dev.azure.com/gvfs/ci/_build/results?buildId=19227&view=results).
=> Update Git to signed Debian package

.github/workflows/continuous-integration.yml
This imitates git/git@cac42e471afa to avoid using the now-deprecated `set-env` construct in our CI workflow.
=> ci: avoid `set-env`

Scalar.Common/Git/GitProcess.cs
The foreground fetch was created by copy/pasting from background
fetch. We didn't notice any problems because users were authenticating
via the /gvfs/config endpoint in most cases. Also, if there was an
existing credential, then they would not hit this issue.
Resolves #463.
=> GitProcess: foreground fetch should be interactive

.github/workflows/continuous-integration.yml, Directory.Build.props
This updates on top of the 20.10.178 release.
Requires build updates from #466.
This actually updates to a better build:
1. It has a new tag `v2.29.0.vfs.0.1`.
2. It was created after `git-for-windows/build-extra` updated with the new GCM Core package.
=> [HOTFIX] Update Git to include GCM Core update

Directory.Build.props
This actually updates to a better build:
1. It has a new tag `v2.29.0.vfs.0.1`.
2. It was created after `git-for-windows/build-extra` updated with the new GCM Core package.
=> Update Git to include GCM Core update

Directory.Build.props, Scalar.FunctionalTests/Categories.cs, Scalar.FunctionalTests/Program.cs, Scalar.FunctionalTests/ScalarTestConfig.cs, Scalar.FunctionalTests/Settings.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/CommitGraphStepTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/FetchStepTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/LooseObjectStepTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/PackfileMaintenanceStepTests.cs, Scalar.FunctionalTests/Tests/EnlistmentPerFixture/TestsWithEnlistmentPerFixture.cs, Scalar.FunctionalTests/Tools/ScalarFunctionalTestEnlistment.cs
In #458, we dropped the `Scalar.Service` application from the macOS platform and depended entirely on `git maintenance start` to initialize background maintenance. This had two issues:
1. The `cron`-based background maintenance does not sufficiently create a user environment for GCM Core to store credentials. This causes it to start loading pop-ups on the hour every hour for the `prefetch` task. This item is handled upstream as `ds/maintenance-part-4`, which creates platform-specific maintenance abilities, including macOS integration with `launchd`/`launchctl`.
2. The maintenance jobs don't look at the shared object cache! While we were depending on `git maintenance run --task=<task>` inside `scalar run <job>`, I forgot that `scalar run` sets `GIT_OBJECT_DIRECTORY` so something inside of …
=> Maintenance: use the correct object directory

.azure-pipelines/templates/osx/build-and-unit-test.yml
Remove the Apple developer certificate installation step from the CI build Azure Pipelines YAML, as it is no longer required. We no longer have any Xcode projects that would use it.
=> Remove Apple certificate install step from build YAML

.github/workflows/continuous-integration.yml, Scalar.Common/Git/GitProcess.cs, Scalar.Installer.Mac/InstallScalar.template.sh
Enable Trace2 logging in Git for the functional test suite.
Then zip up the logs and store in as a single artifact.
=> Enable Trace2 logging of functional tests

Scalar.Common/Git/GitFeatureFlags.cs, Scalar.Common/Git/GitProcess.cs, Scalar.Common/Git/GitVersion.cs, Scalar.Common/Maintenance/ConfigStep.cs, Scalar.FunctionalTests/Tools/GitHelpers.cs, Scalar.UnitTests/Common/GitVersionTests.cs, Scalar/CommandLine/CloneVerb.cs, Scalar/CommandLine/RunVerb.cs, Scalar/CommandLine/ScalarVerb.cs
This expands the `GitVersion` parser to include an `Extra` string. This will contain anything after `2.X.Y.vfs.Z.W`. For instance, the tag `v2.30.0.vfs.0.0.exp` contains the builtin FS Monitor feature (see microsoft/git#289).
To enable experimental features, we check the new `feature.scalar` config setting. This has a few modes:
1. `feature.scalar=false` implies we want to disable optional features like FS Monitor.
2. `feature.scalar=true` or unset implies we want to use our default values, like using Watchman for FS Monitor.
3. `feature.scalar=experimental` means we should use available experimental features like FS Monitor. In the future, this could also include early versions of sparse-index.
After using `git config` to set the appropriate `feature.scalar` value locally, users can run …
=> Enable experimental features through `features.scalar=experimental`

.github/workflows/continuous-integration.yml, Dependencies.props, Scalar.Common/Scalar.Common.csproj, Scalar.Installer.Mac/Scalar.Installer.Mac.csproj, Scalar.Installer.Windows/Scalar.Installer.Windows.csproj, nuget.config
We don't need this feed, and it is causing build problems during
release.
=> nuget.config: drop internal feed

docs/troubleshooting.md
Discussed with @derrickstolee and agreed this change is beneficial pending @prplr's approval, as it will give users a destination to which to send `scalar diagnose` logs.
=> Adding git-client alias to troubleshooting docs

Scalar.Common/Maintenance/ConfigStep.cs
The generation number v2 is better for algorithmic reasons, but it is
backwards-compatible with version 1 and in doing so requires reading
more data from disk. That extra data load causes a performance
degradation in the typical case.
Let's avoid that for now, until a non-backwards-compatible version is
ready that avoids this performance problem.
> This didn't quite make it in before the release branch was created.
=> [HOTFIX] ConfigStep: commitGraph.generationVersion=1

Scalar.Common/Maintenance/ConfigStep.cs
The generation number v2 is better for algorithmic reasons, but it is
backwards-compatible with version 1 and in doing so requires reading
more data from disk. That extra data load causes a performance
degradation in the typical case.
Let's avoid that for now, until a non-backwards-compatible version is
ready that avoids this performance problem.
=> ConfigStep: commitGraph.generationVersion=1

.azure-pipelines/templates/osx/build-and-unit-test.yml, .azure-pipelines/templates/osx/pack.signed/step5-dist.yml, .azure-pipelines/templates/win/build-and-unit-test.yml, .azure-pipelines/templates/win/install-git-package.bat, .azure-pipelines/templates/win/install-git-package.sh, Scalar.Installer.Mac/Scalar.Installer.Mac.csproj, Scalar.Installer.Mac/dist.sh, Scalar.Installer.Windows/Scalar.Installer.Windows.csproj
This should also fix the microsoft.scalar-release pipeline.
See #494 for the version into `main`.
After many attempts, I now have this working with [the `microsoft.scalar-release` build in Azure Pipelines](https://dev.azure.com/mseng/Scalar/_build/results?buildId=14679562&view=results)
=> [HOTFIX] Fix macOS build around Git installer package

Directory.Build.props
Consume v2.31.0.vfs.0.1 version of microsoft/git (build 2.20210322.1).
=> Upgrade to microsoft/git 2.20210322.1 (v2.31.0.vfs.0.1)

Scalar.Common/Git/GitVersion.cs, Scalar.UnitTests/Common/GitVersionTests.cs
Resolves #501.
The feature flag was originally introduced in cd0e476870c204c5e1452493bccf83c29c3a2562 (#398) but at that time we didn't know if the core Git client was ready, so we didn't enable it for versions of Git that did not include the `.vfs.` platform.
Fix this since background maintenance is now available on all platforms on v2.31.0 and later.
=> GitVersion: enable maintenance flag for v2.31.0+

Directory.Build.props
This version will be released after these tests pass. Includes changes to how we upgrade Git.
=> Update Git to v2.31.1.vfs.0.3

Scalar.FunctionalTests/Tests/MultiEnlistmentTests/ScalarCloneFromGithub.cs
The 'main' branch no longer contains the expected directories.
=> ScalarCloneFromGitHub: use 'for-tests' branch

Directory.Build.props
This uses a `-pr` build, but we can relax that now that we are not shipping from this repository any more.
This version specifically includes microsoft/git#378 which retries fetches. This will unblock changes such as #513 which are failing with this rather frequent flakiness.
=> Update Git to a version that retries fetches

Scalar.FunctionalTests/Tests/EnlistmentPerFixture/SparseSetTests.cs
Something strange happens with the MergeChangesOutOfTheConeWithConflict
when run in sequence with the other tests in this class. Some edited
files from previous tests cause confusion when running 'git merge'.
For some reason, this is causing a behavior change with the
sparse-index, but it seems that either behavior would be acceptable
here.
Another thing we could do is remove the `ShouldContain("Merge conflict")`
line and the test passes that way, too. This seems like a more robust
solution.
This will resolve the last failing test in microsoft/git#388 for Linux and macOS.
There is one more strange error happening on Windows. Will investigate.
=> SparseSetTests: Ensure no edits remain before merge

.github/workflows/continuous-integration.yml, Directory.Build.props, Scalar.FunctionalTests/Tests/GitCommands/GitCommandsTests.cs
See microsoft/git#460 for a failing test due to changes to how `git add` works upstream.
=> GitCommandsTests: use 'git add --sparse'

Scalar.FunctionalTests/Tests/EnlistmentPerFixture/DiagnoseTests.cs
I recently ran into [hard-to-diagnose problems](https://github.com/dscho/git/actions/runs/2297168173), thanks to a construct that fails to provide helpful information in case of a regression. This fixes that.
=> DiagnoseTests: make failure more helpful

Dependencies.props
Update newtonsoft.json to 13.0.1 to mitigate exposure to security vulnerability associated with previous versions.
=> dependencies: update newtonsoft.json

Dependencies.props, Scalar.FunctionalTests/Scalar.FunctionalTests.csproj
We got an internal report for a vulnerability:
```
A remote code execution vulnerability exists when parsing certain
types of graphics files. This vulnerability only exists on systems
running on MacOS or Linux. This CVE ID is unique from CVE-2021-26701.
```
The report also included this statement:
```
Root dependencies for System.Drawing.Common
Microsoft.PowerShell.SDK 6.2.2
Microsoft.Windows.Compatibility 2.1.1
```
It turns out that we don't need these dependencies anymore, so we can remove them.
=> Remove unused packages that have vulnerable dependencies

.github/workflows/homebrew-release.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve #530 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
=> Replace deprecated command with environment file

Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs, Scalar.FunctionalTests/Tools/ControlGitRepo.cs
A new advice message is coming to Git and `microsoft/git` which can lead to different `stderr` in an expected way.
By configuring this advice message to be quiet, we can match the behavior across full and sparse Scalar enlistments.
=> Tests: disable advice message
